#!/bin/sh
set -euf

##
# Launch tmux with a sesson and windows suitable for Rails development.
#
# Syntax:
#
#     tmux-start-rails [session-name]
#
# Example:
#
#     cd my_rails_app
#     tmux-start-rails
#
#
# ## What this does
#
# The script attaches to session-name.
#
#   * If the session doesn't exist, then this creates it.
#   * The _session-name_ defaults to the basename of the pwd.
#
# The script launches these windows with these commands:
#
#   * 1:qq=quickies = such as for shells and command line interfaces.
#   * 2:ww=wizards = such as for dashboards, trackers, messengers.
#   * 3:ee=editors = `$EDITOR`
#   * 4:rr=runners = `$RAILS test`
#   * 5:cc=consoles = `$RAILS console`
#   * 6:dd=databases = `$RAILS db -p`
#   * 7:ss=servers = `$RAILS server`
#   * 8:ll=loggers = loggers = `tail -f log/$RAILS_ENV.log`
#   * 9:oo=options = other options, such as extras, helpers, utilities
#
# Mnemonics on a popular U.S. English language keyboard layout:
#
#   * 1 = ! = qq = quickies = exclamation means imperative.
#   * 2 = @ = ww = wizards = at-sign means what's happening here?
#   * 3 = # = ee = editors = hash sign looks like a code comment.
#   * 4 = $ = rr = runners = dollar sign looks like initials "SI" for "Ship It".
#   * 5 = % = cc = consoles = percent sign looks like a batting percentage.
#   * 6 = ^ = dd = databases = carat looks like a data warehouse.
#   * 7 = & = ss = servers = ampersand means background process.
#   * 8 = * = ll = loggers = asterisk looks like an annotation.
#   * 9 = ( = oo = options = parenthesis means an aside.
#
# ## Commands
#
# This script will choose the "rails" command in order:
#
#   * If the $RAILS env var is set, then use it.
#   * If "bin/rails" is runnable, then use it.
#   * If "bundle" command is runnable, then use "bundle exec rails".
#
# This script will do the same as above for the "rake" command.
#
#
# ## Tracking
#
# Program: tmux-start-rails
# Version: 5.0.0
# Created: 2013-08-02T00:00:00Z
# Updated: 2022-07-25T00:16:53Z
# License: GPL-2.0-or-later or contact us for custom
# Contact: Joel Parker Henderson ~ joel@joelparkerhenderson.com
##

command -v "tmux-start" >/dev/null 2>&1 || 
echo "Command needed: tmux-start. Get it at https://github.com/sixarm/tmux-start."

# The session name default is the current directory's basename.
session_name=${1-$(basename "$(pwd)")}

# Choose an editor, or none.
if [ -z ${EDITOR+_} ]; then
  EDITOR=""
fi

# Choose a command for bundle.
if [ -z ${BUNDLE_EXEC+_} ]; then
  if cmd bundle; then
    BUNDLE_EXEC="bundle exec"
  else
    BUNDLE_EXEC=""
  fi
fi

# Choose a commmand for rails.
if [ -z ${RAILS+_} ]; then
  if [ -x 'bin/rails' ]; then
    RAILS="bin/rails"
  else
    RAILS="$BUNDLE_EXEC rails"
  fi
fi

# Choose a commmand for rake.
if [ -z ${RAKE+_} ]; then
  if [ -x 'bin/rake' ]; then
    RAKE="bin/rake"
  else
    RAKE="$BUNDLE_EXEC rake"
  fi
fi

# The Rails environment default is "development".
RAILS_ENV=${RAILS_ENV:-development}

tmux-start "$session_name" \
"qq=quickies" ":" \
"ww=watchers" ":" \
"ee=editors" "$EDITOR" \
"rr=runners" "$RAILS test" \
"cc=consoles" "$RAILS console" \
"dd=databases" "$RAILS db" \
"ss=servers" "$RAILS server" \
"ll=loggers" "tail -f log/$RAILS_ENV.log" \
"op=options" ":"
